In [1]:
import numpy as np
import pandas as pd

In [9]:
# Pauli operators
pauli_x = .5*np.matrix('0,1;1,0')
pauli_y = .5*np.matrix('0,1j;-1j,0')
pauli_z = .5*np.matrix('1,0;0,-1')

In [96]:
# Spin raising and lowering operators
Splus = pauli_x + 1j*pauli_y
Sminus = pauli_x - 1j*pauli_y

### Diagonalized XX Hamiltonian

In [97]:
N = 4
m = np.arange(1,N,1)
k = lambda m : 2*np.pi*m/N

# dk = 1/np.sqrt(N) * np.sum( np.exp(-1j*k*m) ) * np.kron(Sminus,np.eye(N-2))
# dk_dag = 1/np.sqrt(N) * np.sum( np.exp(1j*k*m) ) * np.kron(Splus, np.eye(N-2))

In [98]:
dk_func = lambda m : 1/np.sqrt(N) * np.exp(-1j*k(m)*m) * np.kron(Sminus,np.eye(N-2))
dk_dag_func = lambda m : 1/np.sqrt(N) * np.exp(-1j*k(m)*m) * np.kron(Splus, np.eye(N-2))

In [106]:
dk_dag_func(1) * dk_func(1)

matrix([[ 0.  +0.000000e+00j,  0.  +0.000000e+00j,  0.  +0.000000e+00j,
          0.  +0.000000e+00j],
        [ 0.  +0.000000e+00j,  0.  +0.000000e+00j,  0.  +0.000000e+00j,
          0.  +0.000000e+00j],
        [ 0.  +0.000000e+00j,  0.  +0.000000e+00j, -0.25-3.061617e-17j,
          0.  +0.000000e+00j],
        [ 0.  +0.000000e+00j,  0.  +0.000000e+00j,  0.  +0.000000e+00j,
         -0.25-3.061617e-17j]])

In [91]:
J = 1
B = 1

for m in range(1,N):
    H = J * np.cos(m - B) * dk_dag_func(m)*dk_func(m)

In [92]:
zero = np.matrix('1;0')
dk_dag_func(1)*dk_func(1)*np.kron(zero, np.eye(2))

matrix([[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]])

In [117]:
np.real(dk_dag_func(1) * dk_func(2))

matrix([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 7.65404249e-17, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.65404249e-17]])

In [116]:
dk_dag_func(1) * dk_func(2)*np.kron(zero, np.eye(2))
# dk_dag_func(2) * dk_func(2)*np.kron(zero, np.eye(2))
# dk_dag_func(3) * dk_func(3)*np.kron(zero, np.eye(2))
# dk_dag_func(4) * dk_func(4)*np.kron(zero, np.eye(2))

matrix([[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]])

In [109]:
dk_dag_func(1) * dk_func(1)

matrix([[ 0.  +0.000000e+00j,  0.  +0.000000e+00j,  0.  +0.000000e+00j,
          0.  +0.000000e+00j],
        [ 0.  +0.000000e+00j,  0.  +0.000000e+00j,  0.  +0.000000e+00j,
          0.  +0.000000e+00j],
        [ 0.  +0.000000e+00j,  0.  +0.000000e+00j, -0.25-3.061617e-17j,
          0.  +0.000000e+00j],
        [ 0.  +0.000000e+00j,  0.  +0.000000e+00j,  0.  +0.000000e+00j,
         -0.25-3.061617e-17j]])

In [20]:
J = 1
B = 1
np.sum((J * np.cos(k-B))) * dk_dag*dk

matrix([[ 0.        +0.j,  0.        +0.j],
        [ 0.        +0.j, -0.67537788+0.j]])

In [21]:
zero = np.matrix('1;0')

In [95]:
dk_dag*dk_dag*zero

TypeError: unsupported operand type(s) for *: 'function' and 'function'

### NV Centre Effective Hamiltonian


$H_{eff} = \kappa \sum_{i=1}^{N-1} \left( \sigma_{+}^{i}\sigma_{-}^{i+1} + \sigma_{-}^{i}\sigma_{+}^{i+1} \right) + g \sum_{j=0,N} \sigma_{+}^{j}\sigma_{-}^{j+1} + \sigma_{-}^{j}\sigma_{+}^{j+1}$

In [78]:
def nv_nitrogen_effective_hamiltonian(N,k,g):
    # Effective Hamiltonian for a spin chain with two register NV spins at either end 
    # of a chain of nitrogen spins
    
    sx = np.matrix('0 1; 1 0')
    sy = np.matrix('0 -1j; 1j 0')
    sz = np.matrix('1 0; 0 -1')
    
    splus = .5*(sx + 1j*sy)
    sminus = .5*(sx - 1j*sy)

    H = np.zeros((2**N,2**N));

    for num in range(0,N-1):
        if num == 0:
            H=H+g*np.kron(splus,np.kron(sminus,np.eye(2**(N-num-2)))) +\
                g*np.kron(sminus,np.kron(splus,np.eye(2**(N-num-2))))
        elif (num>0) & (num <= N-1):
            H=H+k*np.kron(np.eye(2**(num)),np.kron(splus,np.kron(sminus,np.eye(2**(N-num-2)))))+\
                k*np.kron(np.eye(2**(num)),np.kron(sminus,np.kron(splus,np.eye(2**(N-num-2)))))
        elif num == N-1:
            H=H+g*np.kron(np.eye(2**(N-num-2)),np.kron(splus,sminus)) +\
                g*np.kron(np.eye(2**(N-num-2)),np.kron(sminus,splus))
    return H

In [79]:
N = 4
g = 1
k = 1
np.real(nv_Heff(N,k,g))

matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0

In [91]:
En = []
for n in range(1,N+1):
    En.append(n*k*np.cos(1*(np.pi/(N+1))))
En

[0.8090169943749475, 1.618033988749895, 2.4270509831248424, 3.23606797749979]

array([ 0.6545085 ,  2.61803399,  5.89057647, 10.47213595])

In [95]:
dt = 1e-06

psi = np.
for t in range(100):
    psi = np.exp(-1j* np.real(En * np.transpose(En)) * t+dt)

In [97]:
psi

array([-0.3836008 -0.9235001j , -0.00397096-0.99999312j,
        0.390923  +0.92042447j,  0.99987485-0.01588321j])